### ISSUE TITLE
A request of paper "TagFog：Textual Anchor Guidance and Fake Outlier Generation for Visual Out-of-distribution Detection"

### ISSUE THREAD

**Issue by v-1024** [Cverchen/TagFog#1]
Dear athour,

Thanks for your remarkable contribution.

I am very interested in your research and would greatly appreciate it if you could share the PDF of your paper or provide me with a link where I can access it. Your work aligns with my research interests, and I believe studying your paper will be beneficial for my own academic pursuits.

Best regards

**Comment by Cverchen** [comment]
Thanks for your interest about our work. Our paper is as follows:
[AAAI2024-TagFog.pdf](https://github.com/Cverchen/TagFog/files/14668496/AAAI2024-TagFog.pdf)
